### PR TITLE
Added Dunfell support

### PR DESCRIPTION
**Pull request by colin-pm**
Updated meta-layer to work with Dunfell (3.1).  Python 2 support was removed to ease maintainability.  Recipes upstream in meta-python have been removed.  Conan recipe updated to 1.32.1.

Signed-off-by: Colin McAllister <colinmca242@gmail.com>

### CODE REVIEW

**Review by danimtb — APPROVED** [review]
LGTM

**Comment by danimtb** [comment]
Thanks for the contribution @colin-pm! I will merge this PR to the master branch and create a `dunfell` branch to "freeze" the changes as that is the general way to do it in yocto

**Comment by danimtb** [comment]
🤔 the CLA webhook was not triggered. I will open/close the PR to see if that fixes it

**Comment by danimtb** [comment]
Now you got it! Please @colin-pm could you check it? thank you 😄

**Comment by colin-pm** [comment]
CLA has been signed.

**Pull request merged**
